# For development testing, after you have created your test accounts
# in the PayPal sandbox, and enabled API access while logged in
# to your test account in the sandbox, you can get this API info
# under the Profile tab of the logged-in PayPal account or at
# https://developer.paypal.com/cgi-bin/devscr?cmd=_certs-session
development:
  :login: "strtho_api1.gmail.com"
  :password: "1363009986"
  :signature: "Af36yZnRSuoz5MOlkNthUgAI9UYsApjrzFfgZb5O-Yyyor8RWiv-f7Ez"
  :test: true
production:
  :login: "strtho_api1.gmail.com"
  :password: "1363009986"
  :signature: "Af36yZnRSuoz5MOlkNthUgAI9UYsApjrzFfgZb5O-Yyyor8RWiv-f7Ez"
  :test: false
test:
  :login: "strtho_api1.gmail.com"
  :password: "1363009986"
  :signature: "Af36yZnRSuoz5MOlkNthUgAI9UYsApjrzFfgZb5O-Yyyor8RWiv-f7Ez"
  :test: true